org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
minecraft_versions=1.21.11
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=purpur-elevator
mod_name=Purpur Elevator
mod_version=1.0.0
mod_release_type=release
maven_group=nl.gjorgdy

# Dependencies
fzzy_config_version=0.7.6+1.21.11