org.gradle.jvmargs=-Xmx1G

minecraft_versions=26.1.2
minecraft_version=26.1.2
loader_version=0.19.1
loom_version=1.16.1
fabric_api_version=0.145.4+26.1.2

mod_id=purpur-elevator
mod_name=Purpur Elevator
mod_description=A simple elevator mod that allows you to quickly travel up and down in the world using purpur blocks.
mod_version=1.0.0
mod_release_type=release
mod_license=MIT
maven_group=nl.gjorgdy
author=Gjorgdy

fzzy_config_version=0.7.6+26.1
dev_auth_version=1.1.0