org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
minecraft_versions=1.21.11
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=purpur-elevator
mod_name=Purpur Elevator
mod_version=0.1.0
mod_release_type=beta
maven_group=nl.gjorgdy

# Dependencies
fabric_api_version=0.140.2+1.21.11
fzzy_config_version=0.7.4-fix2+1.21.11